# Generated by Django 4.0.3 on 2022-04-11 07:13

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateprojects', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project_name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('technologies', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
